### ISSUE TITLE
[Bug]: no notes detected

### ISSUE THREAD

**Issue by danielb2** [rxliuli/joplin-utils#65]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

No notes detected error on the left side panel when clicking J extension

`Joplin 2.9.17 (prod, darwin)`

( note, you should probably remind people filing bugs to mention joplin version )

### Steps to reproduce the behavior

1. open vscode
2. click joplin extension

### log file

<details>
<summary>VScode errors - Invalid "token" parameter</summary>
{"level":"error","message":"command error: joplinNote.search, status: 403, url: http://localhost:41184/notes?fields=id,title&limit=20&order_by=user_updated_time&order_dir=DESC&token=[FILTERED]\nstatusText: {\"error\":\"Invalid \\\"token\\\" parameter: \\n\\nError: Invalid \\\"token\\\" parameter\\n    at Api.checkToken_ (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:185:19)\\n    at Api.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:148:18)\\n    at Generator.next (<anonymous>)\\n    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:8:71\\n    at new Promise (<anonymous>)\\n    at __awaiter (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:4:12)\\n    at Api.route (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/services/rest/Api.js:100:16)\\n    at ClipperServer.<anonymous> (/Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/ClipperServer.js:168:58)\\n    at Generator.next (<anonymous>)\\n    at /Applications/Joplin.app/Contents/Resources/app.asar/node_modules/@joplin/lib/ClipperServer.js:8:71\"}","pluginVersion":"1.1.0"}

</details>

### Additional context

this plugin has worked for me before and I didn't change anything that I'm aware.

Trying on curl, removing the token parameter generates an error saying it's missing. so it looks like it's a joplin issue

**Comment by danielb2** [comment]
OK, I just realized this is because I also use this extension on my laptop.
