### ISSUE TITLE
[Bug]:  Blob is not defined when upload image

### ISSUE THREAD

**Issue by roooooc** [rxliuli/joplin-utils#79]
### Confirmation

- [X] I checked [FAQ](https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/faq.html)

### The tool/kit where the error occurred

joplin-vscode-plugin

### Describe the bug

vscode pop up notification Blob is not defined when upload image

joplin-vscode-plugin 1.2.1 and 1.2

### Steps to reproduce the behavior

1. copy a picture
2. ctrl+alt+u 
3. vscode pop up notification “Blob is not defined”

### log file

**vscode log**

2023-09-05 18:02:00.957 [error] ReferenceError: Blob is not defined
	at UploadResourceUtil.uploadByPath (D:\user\Scoop\persist\vscode\data\extensions\rxliuli.joplin-vscode-plugin-1.2.1\dist\extension.js:39082:17)
	at UploadResourceService.uploadImageFromClipboard (D:\user\Scoop\persist\vscode\data\extensions\rxliuli.joplin-vscode-plugin-1.2.1\dist\extension.js:39178:60)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async D:\user\Scoop\persist\vscode\data\extensions\rxliuli.joplin-vscode-plugin-1.2.1\dist\extension.js:40307:16
	at async a.h (d:\user\Scoop\apps\vscode\1.81.1\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:77769) joplin.uploadImageFromClipboard {"value":"rxliuli.joplin-vscode-plugin","_lower":"rxliuli.joplin-vscode-plugin"}

**combined.log**
{"level":"info","message":"command execute: joplin.search"}
{"level":"info","message":"HandlerService.openNote: 9260f8bada084f37b04af303644ae0e4"}
{"level":"info","message":"openNote start, id: 9260f8bada084f37b04af303644ae0e4, title: testnote"}
{"level":"info","message":"openNote write tempFile: testnote.md"}
{"level":"info","message":"openNote open tempFile"}
{"level":"info","message":"provideDocumentLinks: "}
{"level":"info","message":"provideDocumentLinks: "}
{"level":"info","message":"provideDocumentLinks: "}
{"level":"info","message":"provideDocumentLinks: "}
{"level":"info","message":"provideDocumentLinks: "}
{"level":"info","message":"command execute: joplin.uploadImageFromClipboard"}
{"level":"error","message":"command error: joplin.uploadImageFromClipboard, Blob is not defined"}

**Comment by rxliuli** [comment]
fixed: https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%401.2.2
